import { Rarity, type CardModel } from "../models/CardModel";

export const Cards: CardModel[] = [
  {
    id: 1,
    name: "T-Rex",
    image: "/public/dino-deck/rex.webp",
    attack: 130,
    defense: 45,
    hp: 130,
    maxHp: 130,
    cost: 130,
    type: "carnivore",
    rarity: Rarity.LEGENDARY,
    description:
      "Predador supremo do Cretáceo, com mordida devastadora e presença dominante no topo da cadeia alimentar.",
  },
  {
    id: 2,
    name: "Mosassauro",
    image: "/public/dino-deck/mosassauro.webp",
    attack: 125,
    defense: 40,
    hp: 145,
    maxHp: 145,
    cost: 125,
    type: "carnivore",
    rarity: Rarity.LEGENDARY,
    description:
      "Gigante dos mares pré-históricos, rápido e letal, dominava os oceanos com força e alcance impressionantes.",
  },
  {
    id: 3,
    name: "Sarcosuchus",
    image: "/public/dino-deck/sarco.webp",
    attack: 90,
    defense: 40,
    hp: 110,
    maxHp: 110,
    cost: 70,
    type: "carnivore",
    rarity: Rarity.RARE,
    description:
      "Crocodiliano gigante que emboscava presas nas margens, combinando força bruta com ataques surpresa.",
  },
  {
    id: 4,
    name: "Estegossauro",
    image: "/public/dino-deck/estegossauro.webp",
    attack: 40,
    defense: 45,
    hp: 120,
    maxHp: 120,
    cost: 65,
    type: "herbivore",
    rarity: Rarity.RARE,
    description:
      "Herbívoro resistente com placas dorsais e cauda espinhosa, focado em defesa e sobrevivência.",
  },
  {
    id: 5,
    name: "Ceratossauro",
    image: "/public/dino-deck/ceratossauro.webp",
    attack: 80,
    defense: 35,
    hp: 100,
    maxHp: 100,
    cost: 70,
    type: "carnivore",
    rarity: Rarity.RARE,
    description:
      "Predador ágil com chifre nasal, equilibrando velocidade e força em ataques diretos.",
  },
  {
    id: 6,
    name: "Ultraraptor",
    image: "/public/dino-deck/ultraraptor.webp",
    attack: 55,
    defense: 20,
    hp: 65,
    maxHp: 65,
    cost: 35,
    type: "carnivore",
    rarity: Rarity.COMMON,
    description:
      "Caçador veloz e oportunista, compensa baixa resistência com ataques rápidos e constantes.",
  },
  {
    id: 7,
    name: "Plesiossauro",
    image: "/public/dino-deck/plesiossauro.webp",
    attack: 70,
    defense: 35,
    hp: 120,
    maxHp: 120,
    cost: 80,
    type: "carnivore",
    rarity: Rarity.EPIC,
    description:
      "Predador marinho de pescoço longo, eficiente em resistência e ataques contínuos.",
  },
  {
    id: 8,
    name: "Giganotossauro",
    image: "/public/dino-deck/giganotossauro.webp",
    attack: 125,
    defense: 40,
    hp: 135,
    maxHp: 135,
    cost: 125,
    type: "carnivore",
    rarity: Rarity.LEGENDARY,
    description:
      "Gigante predador do Cretáceo, rival do T-Rex, com força bruta e mordidas devastadoras em combate direto.",
  },
  {
    id: 9,
    name: "Barionix",
    image: "/public/dino-deck/barionix.webp",
    attack: 80,
    defense: 35,
    hp: 110,
    maxHp: 110,
    cost: 70,
    type: "carnivore",
    rarity: Rarity.RARE,
    description:
      "Predador semiaquático com garras e dentes afiados, especializado em ataques nas águas rasas.",
  },
  {
    id: 10,
    name: "Terezinossauro",
    image: "/public/dino-deck/terezinossauro.webp",
    attack: 75,
    defense: 40,
    hp: 130,
    maxHp: 130,
    cost: 90,
    type: "herbivore",
    rarity: Rarity.EPIC,
    description:
      "Gigante herbívoro com garras colosais, construído para defesa absoluta e sobrevivência em qualquer ambiente.",
  },
  {
    id: 11,
    name: "Yutiranus",
    image: "/public/dino-deck/yutiranus.webp",
    attack: 95,
    defense: 35,
    hp: 120,
    maxHp: 120,
    cost: 95,
    type: "carnivore",
    rarity: Rarity.EPIC,
    description:
      "Predador ágil e agressivo, com reflexos rápidos e ataques ferozes contra qualquer tipo de presa.",
  },
  {
    id: 12,
    name: "Espinossauro",
    image: "/public/dino-deck/espinossauro.webp",
    attack: 118,
    defense: 35,
    hp: 140,
    maxHp: 140,
    cost: 125,
    type: "carnivore",
    rarity: Rarity.LEGENDARY,
    description:
      "Majestoso predador semiaquático com vela dorsal impressionante, dominando tanto ambientes terrestres quanto aquáticos com poder devastador.",
  },
  {
    id: 13,
    name: "Triceratops",
    image: "/public/dino-deck/triceratops.webp",
    attack: 65,
    defense: 50,
    hp: 110,
    maxHp: 110,
    cost: 75,
    type: "herbivore",
    rarity: Rarity.RARE,
    description:
      "Herbívoro imponente com três chifres poderosos e escudo craniano, mestre da defesa com cargas devastadoras contra predadores.",
  },
  {
    id: 14,
    name: "Dilofossauro",
    image: "/public/dino-deck/dilofossauro.webp",
    attack: 40,
    defense: 25,
    hp: 60,
    maxHp: 60,
    cost: 25,
    type: "carnivore",
    rarity: Rarity.COMMON,
    description:
      "Um predador ágil e implacável das florestas pré-históricas. Suas cristas gêmeas impressionantes e mandíbulas afiadas garantem que ele seja uma ameaça rápida e perigosa para qualquer presa.",
  },
  {
    id: 15,
    name: "Anquilossauro",
    image: "/public/dino-deck/anquilossauro.webp",
    attack: 55,
    defense: 55,
    hp: 160,
    maxHp: 160,
    cost: 90,
    type: "herbivore",
    rarity: Rarity.EPIC,
    description:
      "Revestido por uma couraça de placas ósseas e espinhos, o Anquilossauro é uma montanha inabalável. Poucos ousam desafiar sua defesa absoluta, pois um único golpe de sua clava caudal é capaz de estilhaçar os ossos até do mais colossal predador.",
  },
  {
    id: 16,
    name: "Compsognathus",
    image: "/public/dino-deck/compsognathus.webp",
    attack: 30,
    defense: 15,
    hp: 45,
    maxHp: 45,
    cost: 20,
    type: "carnivore",
    rarity: Rarity.COMMON,
    description:
      "Pequeno e ágil, ataca rápido mas não resiste a confrontos diretos.",
  },
  {
    id: 17,
    name: "Kaprosuchus",
    image: "/public/dino-deck/kaprosuchus.webp",
    attack: 55,
    defense: 25,
    hp: 80,
    maxHp: 80,
    cost: 35,
    type: "carnivore",
    rarity: Rarity.COMMON,
    description:
      "Crocodiliano terrestre agressivo, combina força e resistência moderada.",
  },
  {
    id: 18,
    name: "Diplodoco",
    image: "/public/dino-deck/diplodoco.webp",
    attack: 40,
    defense: 40,
    hp: 180,
    maxHp: 180,
    cost: 95,
    type: "herbivore",
    rarity: Rarity.EPIC,
    description:
      "Gigante herbívoro de pescoço longo, possui resistência colossal e domina batalhas pela durabilidade.",
  },
  {
    id: 19,
    name: "Troodon",
    image: "/public/dino-deck/trodonte.webp",
    attack: 50,
    defense: 20,
    hp: 60,
    maxHp: 60,
    cost: 40,
    type: "carnivore",
    rarity: Rarity.COMMON,
    description:
      "Predador inteligente e letal, causa dano alto mas é extremamente frágil.",
  },
  {
    id: 20,
    name: "Argentinossauro",
    image: "/public/dino-deck/argentinossauro.webp",
    attack: 35,
    defense: 50,
    hp: 240,
    maxHp: 240,
    cost: 130,
    type: "herbivore",
    rarity: Rarity.LEGENDARY,
    description:
      "Gigante herbívoro do Cretáceo tardio, um dos maiores sauropodes já descobertos. Seu tamanho colossal garante resistência formidável e defesa quase impenetrável, enquanto ataques são lentos mas devastadores.",
  },
  {
    id: 21,
    name: "Megalodon",
    image: "/public/dino-deck/megalodon.webp",
    attack: 125,
    defense: 45,
    hp: 150,
    maxHp: 150,
    cost: 125,
    type: "carnivore",
    rarity: Rarity.LEGENDARY,
    description:
      "Gigante predador dos oceanos, com mandíbulas capazes de esmagar presas enormes. Poderoso e resiliente, domina combates aquáticos com força bruta.",
  },
  {
    id: 22,
    name: "Carnotauro",
    image: "/public/dino-deck/carnotauro.webp",
    attack: 85,
    defense: 30,
    hp: 100,
    maxHp: 100,
    cost: 75,
    type: "carnivore",
    rarity: Rarity.RARE,
    description:
      "Predador bípedo do final do Cretáceo, conhecido pelos chifres sobre os olhos e pela mordida poderosa. Ágil e feroz, prefere emboscadas rápidas e golpes certeiros.",
  },
  {
    id: 23,
    name: "Purussaurus",
    image: "/public/dino-deck/purussaurus.webp",
    attack: 95,
    defense: 35,
    hp: 120,
    maxHp: 120,
    cost: 95,
    type: "carnivore",
    rarity: Rarity.EPIC,
    description:
      "Crocodiliano gigante do Mioceno, com mordida esmagadora e corpo blindado. Resistente e brutal, domina combates de proximidade com força e resistência superiores.",
  },
  {
    id: 24,
    name: "Terrorbird",
    image: "/public/dino-deck/terrorbird.webp",
    attack: 70,
    defense: 30,
    hp: 95,
    maxHp: 95,
    cost: 65,
    type: "carnivore",
    rarity: Rarity.RARE,
    description:
      "Ave predadora gigante, de pernas poderosas e bico mortal, que domina ataques rápidos e imprevisíveis em terreno aberto.",
  },
  {
    id: 25,
    name: "Deinonychus",
    image: "/public/dino-deck/deinonychus.webp",
    attack: 55,
    defense: 30,
    hp: 85,
    maxHp: 85,
    cost: 60,
    type: "carnivore",
    rarity: Rarity.RARE,
    description:
      "Caçador veloz e feroz com garras de foice, especializado em ataques coordenados e perseguições implacáveis.",
  },
];
