import { Rarity, type CardModel } from "../models/CardModel";

export const Cards: CardModel[] = [
  {
    id: 1,
    name: "T-Rex",
    image: "/public/dino-deck/rex.webp",
    attack: 135,
    defense: 70,
    hp: 120,
    cost: 120,
    type: "carnivore",
    rarity: Rarity.LEGENDARY,
    description:
      "Predador supremo do Cretáceo, com mordida devastadora e presença dominante no topo da cadeia alimentar.",
  },
  {
    id: 2,
    name: "Mosassauro",
    image: "/public/dino-deck/mosassauro.webp",
    attack: 125,
    defense: 65,
    hp: 135,
    cost: 125,
    type: "carnivore",
    rarity: Rarity.LEGENDARY,
    description:
      "Gigante dos mares pré-históricos, rápido e letal, dominava os oceanos com força e alcance impressionantes.",
  },
  {
    id: 3,
    name: "Sarcosuchus",
    image: "/public/dino-deck/sarco.webp",
    attack: 85,
    defense: 65,
    hp: 105,
    cost: 75,
    type: "carnivore",
    rarity: Rarity.RARE,
    description:
      "Crocodiliano gigante que emboscava presas nas margens, combinando força bruta com ataques surpresa.",
  },
  {
    id: 4,
    name: "Estegossauro",
    image: "/public/dino-deck/estegossauro.webp",
    attack: 55,
    defense: 95,
    hp: 130,
    cost: 55,
    type: "herbivore",
    rarity: Rarity.COMMON,
    description:
      "Herbívoro resistente com placas dorsais e cauda espinhosa, focado em defesa e sobrevivência.",
  },
  {
    id: 5,
    name: "Ceratossauro",
    image: "/public/dino-deck/ceratossauro.webp",
    attack: 90,
    defense: 60,
    hp: 100,
    cost: 80,
    type: "carnivore",
    rarity: Rarity.RARE,
    description:
      "Predador ágil com chifre nasal, equilibrando velocidade e força em ataques diretos.",
  },
  {
    id: 6,
    name: "Ultraraptor",
    image: "/public/dino-deck/ultraraptor.webp",
    attack: 50,
    defense: 40,
    hp: 80,
    cost: 35,
    type: "carnivore",
    rarity: Rarity.COMMON,
    description:
      "Caçador veloz e oportunista, compensa baixa resistência com ataques rápidos e constantes.",
  },
  {
    id: 7,
    name: "Plesiossauro",
    image: "/public/dino-deck/plesiossauro.webp",
    attack: 75,
    defense: 65,
    hp: 120,
    cost: 95,
    type: "carnivore",
    rarity: Rarity.EPIC,
    description:
      "Predador marinho de pescoço longo, eficiente em resistência e ataques contínuos.",
  },
  {
    id: 8,
    name: "Giganotossauro",
    image: "/public/dino-deck/giganotossauro.webp",
    attack: 122,
    defense: 75,
    hp: 125,
    cost: 95,
    type: "carnivore",
    rarity: Rarity.LEGENDARY,
    description:
      "Gigante predador do Cretáceo, rival do T-Rex, com força bruta e mordidas devastadoras em combate direto.",
  },
  {
    id: 9,
    name: "Barionix",
    image: "/public/dino-deck/barionix.webp",
    attack: 78,
    defense: 68,
    hp: 110,
    cost: 70,
    type: "carnivore",
    rarity: Rarity.RARE,
    description:
      "Predador semiaquático com garras e dentes afiados, especializado em ataques nas águas rasas.",
  },
  {
    id: 10,
    name: "Terezinossauro",
    image: "/public/dino-deck/terezinossauro.webp",
    attack: 45,
    defense: 105,
    hp: 145,
    cost: 75,
    type: "herbivore",
    rarity: Rarity.EPIC,
    description:
      "Gigante herbívoro com garras colosais, construído para defesa absoluta e sobrevivência em qualquer ambiente.",
  },
  {
    id: 11,
    name: "Yutiranus",
    image: "/public/dino-deck/yutiranus.webp",
    attack: 88,
    defense: 62,
    hp: 105,
    cost: 80,
    type: "carnivore",
    rarity: Rarity.EPIC,
    description:
      "Predador ágil e agressivo, com reflexos rápidos e ataques ferozes contra qualquer tipo de presa.",
  },
  {
    id: 12,
    name: "Espinossauro",
    image: "/public/dino-deck/espinossauro.webp",
    attack: 110,
    defense: 80,
    hp: 128,
    cost: 100,
    type: "carnivore",
    rarity: Rarity.LEGENDARY,
    description:
      "Majestoso predador semiaquático com vela dorsal impressionante, dominando tanto ambientes terrestres quanto aquáticos com poder devastador.",
  },
  {
    id: 13,
    name: "Triceratops",
    image: "/public/dino-deck/triceratops.webp",
    attack: 65,
    defense: 90,
    hp: 90,
    cost: 75,
    type: "herbivore",
    rarity: Rarity.RARE,
    description:
      "Herbívoro imponente com três chifres poderosos e escudo craniano, mestre da defesa com cargas devastadoras contra predadores.",
  },
];
